apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-dist-job
  namespace: pytorch 
spec:
  runPolicy:
    cleanPodPolicy: Running
  
  pytorchReplicaSpecs:
    Master:                       # 마스터는 GPU 연산 작업에는 참여하지 않는다. GPU Toleration 설정 불필요
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          # --- [수정] NodeSelector 추가 (gpu 강제 지정) ---
          nodeSelector:
            karpenter.sh/nodepool: gpu
          # -----------------------------------------------------
          tolerations:            # GPU Toleration 설정 
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"
          containers:
          - name: pytorch
            image: public.ecr.aws/deep-learning-containers/pytorch-training:2.8.0-gpu-py312-cu129-ubuntu22.04-ec2-v1.0
            command: ["/bin/bash", "-c"] 
            args: 
              - |
                git clone github.com /workspace/code    
                python /workspace/code/training.py
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"    
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          # --- [수정] NodeSelector 추가 (gpu 강제 지정) ---
          nodeSelector:
            karpenter.sh/nodepool: gpu
          # -----------------------------------------------------
          tolerations:            # GPU Toleration 설정 
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"
          containers:
          - name: pytorch
            image: public.ecr.aws/deep-learning-containers/pytorch-training:2.8.0-gpu-py312-cu129-ubuntu22.04-ec2-v1.0
            command: ["/bin/bash", "-c"] 
            args: 
              - |
                git clone github.com /workspace/code    
                python /workspace/code/training.py
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"
