apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-ddp-job
  namespace: pytorch 
spec:
  runPolicy:
    cleanPodPolicy: Running
  
  pytorchReplicaSpecs:
    Master:                       # 마스터는 GPU 연산 작업에는 참여하지 않는다. GPU Toleration 설정 불필요
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: pytorch
            image: pytorch/pytorch:2.9.1-cuda12.6-cudnn9-runtime
            command: ["/bin/bash", "-c"] 
            args: 
              - |
                git clone github.com /workspace/code    
                cd /workspace/code/training-on-eks/samples
                python mnist-ddp.py
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          tolerations:            # GPU Toleration 설정 
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "gpu-workload"
            operator: "Exists"
            effect: "NoSchedule"
          containers:
          - name: pytorch
            image: pytorch/pytorch:2.9.1-cuda12.6-cudnn9-runtime
              command: ["/bin/bash", "-c"] 
            args: 
              - |
                git clone github.com /workspace/code    
                cd /workspace/code/training-on-eks/samples
                python mnist-ddp.py
            resources:
              limits:
                nvidia.com/gpu: "1"
              requests:
                nvidia.com/gpu: "1"
